name:                 bombbusters
version:              0.1.0.0
visibility:           public
id:                   bombbusters-0.1.0.0-inplace
key:                  bombbusters-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           joshuarebay@icloud.com
author:               Joshua Rebay
category:             Game
abi:                  inplace
exposed:              True
exposed-modules:
    BenchmarkLog BotLogic.BotTypes BotLogic.ConstraintSolver
    BotLogic.Inference BotLogic.Interface BotLogic.KnowledgeBase
    BotLogic.Strategies Config GameLogic.Actions GameLogic.Core
    GameLogic.Display GameLogic.Equipment GameLogic.Input
    GameLogic.Util GameLoop InitGame Types

import-dirs:
    /home/joshi/Desktop/BombBusters/dist-newstyle/build/x86_64-linux/ghc-9.10.3/bombbusters-0.1.0.0/build

library-dirs:
    /home/joshi/Desktop/BombBusters/dist-newstyle/build/x86_64-linux/ghc-9.10.3/bombbusters-0.1.0.0/build

library-dirs-static:
    /home/joshi/Desktop/BombBusters/dist-newstyle/build/x86_64-linux/ghc-9.10.3/bombbusters-0.1.0.0/build

dynamic-library-dirs:
    /home/joshi/Desktop/BombBusters/dist-newstyle/build/x86_64-linux/ghc-9.10.3/bombbusters-0.1.0.0/build

data-dir:             /home/joshi/Desktop/BombBusters/.
hs-libraries:         HSbombbusters-0.1.0.0-inplace
depends:
    aeson-2.3.0.0-8f4b07c2fce23ead2612183093b78ae9a447fc46eb1767e1142566564e728bd1
    ansi-terminal-1.1.5-0d75079a20fd7c78d78f390617d21b98faaf3e65c83ab9449d019d6b06eb7218
    base-4.20.2.0-127e bytestring-0.12.2.0-825f containers-0.7-bf99
    directory-1.3.8.5-fe9a filepath-1.5.4.0-3bd9 mtl-2.3.1-bcd6
    pretty-simple-4.1.4.0-623cea80862b866b07e7ee8f22b472edbaa9e1fcb3896ccf30ded3628f42f52b
    random-1.3.1-30e7a3c79f5feeb0d0e3b538b44bad5ec36f3ac7801869de67508646ed9bd3ed
    random-shuffle-0.0.4-80d15c10b943585207b4b5735b0fbce80285a72a70b88fd12455a4e86fddad2b
    sbv-14.1-80d99f2ae570a5a8c4ac688989e24319038aaba01228d1769ddfddc4e0ebb851
    time-1.12.2-c96f

haddock-interfaces:
    /home/joshi/Desktop/BombBusters/dist-newstyle/build/x86_64-linux/ghc-9.10.3/bombbusters-0.1.0.0/doc/html/bombbusters/bombbusters.haddock

haddock-html:
    /home/joshi/Desktop/BombBusters/dist-newstyle/build/x86_64-linux/ghc-9.10.3/bombbusters-0.1.0.0/doc/html/bombbusters
